development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV.fetch("DATABASE_NAME", "tallysheet") %>
  pool: 5
  username: <%= ENV.fetch("DATABASE_USER", "tally") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "sheet!") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  <% unless ENV["DATABASE_HOST"] %>
  socket: /var/run/mysqld/mysql.sock
  <% end %>

test:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV.fetch("DATABASE_NAME", "tallysheet_test") %>
  pool: 5
  username: <%= ENV.fetch("DATABASE_USER", "tally") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "sheet!") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  <% unless ENV["DATABASE_HOST"] %>
  socket: /var/run/mysqld/mysql.sock
  <% end %>

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV.fetch("DATABASE_NAME", "tallysheet") %>
  pool: 5
  username: <%= ENV.fetch("DATABASE_USER", "tally") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "sheet!") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  <% unless ENV["DATABASE_HOST"] %>
  socket: /var/run/mysqld/mysql.sock
  <% end %>
